---
# Docker Image Configuration
docker_image_name: "aws_beanstalk/current-app"
docker_image_tag: "latest"                    # Use specific version instead of 'latest'

# Application Configuration
repository_url: "https://github.com/your/repository.git"
docker_build_context: "{{ playbook_dir }}/../../docker/"  # Path to Dockerfile location

# Container Runtime Configuration
container_name: "jolly_lamport"
container_ports:
  - "80:80"       # Host:Container port mapping
container_env:
  NODE_ENV: "production"

# Resource Limits
container_memory: "512m"
container_cpu: "0.5"

# Health Check
health_check_interval: "30s"
health_check_timeout: "10s"
health_check_retries: 3